### PR TITLE
Fix deprecation warnings for react >= 15.5.0

### PR DESCRIPTION
**Pull request by y-yagi**
Hi.

In React v15.5.0, `React.PropTypes` and `React.createClass` became deprecate.
So I migrated to `prop-types` package and `create-react-class`  package.

Ref: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

### CODE REVIEW

**Comment by benjycui** [comment]
Actually, I am worrying about this. If we migrate to `prop-types` and `create-react-class` directly, this mean we introduce a breaking changes, and developer have to upgrade to `React@15.5+`

**Comment by afc163** [comment]
It is not a a breaking change.

**Comment by benjycui** [comment]
> If we migrate to prop-types and create-react-class directly, developers have to upgrade to React@15.5+

**Comment by afc163** [comment]
> If we migrate to prop-types and create-react-class directly, developers have to upgrade to React@15.5+

They don't have to do that, prop-types and create-react-class don't depend on react@15.5 or as its peerDeps.

**Comment by yesmeck** [comment]
@yiminghe 需要发个版本

**Pull request merged**
